use_frameworks!

platform :ios, '10.0'

target 'LanguageSet_Example' do
  pod 'LanguageSet', :path => '../'

  target 'LanguageSet_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
